# Conda environment for Multi-Driver Stochastic Weather Generator
#
# Create:   conda env create -f environment.yaml
# Activate: conda activate multidriver_swg
# Update:   conda env update -f environment.yaml
# Remove:   conda deactivate && conda env remove -n multidriver_swg
name: multidriver_swg
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # development tools
  - ruff
  - pytest
  - coverage
  - ipdb
  - pip:
      - -e .
